---
name: Master Variant WorkFlow

on:
  push:
    branches:
      - master

jobs:
  superlinter:
    runs-on: ubuntu-latest
    env:
      RUN_LOCAL: true
    name: Super-Linter
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Superlinter
        id: superlinter
        uses: github/super-linter@v3.13.2
